-- CRIACAO DA TABLESPACE E DO USUARIO DE ACESSO AO BANCO DE DADOS DO SISTEMA
CREATE TABLESPACE SGRI DATAFILE 'C:\oraclexe\oradata\XE\SGRI.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M;
CREATE USER SGRI IDENTIFIED BY SGRI DEFAULT TABLESPACE SGRI;
GRANT DBA TO SGRI;

-- TABELA DE USUARIOS: ESTA TABELA DESCREVE TODOS OS USUÁRIOS DO SISTEMA, ASSIM COMO ESTA É USADA PARA SE VERIFICAR O NÍVEL DE PERMISSÃO DE ACESSO AO 
-- SISTEMA.
CREATE TABLE USUARIO (
	CDUSUARIO         INTEGER     PRIMARY KEY,
	NMUSUARIO         VARCHAR(35) NOT NULL,
	SENHA             VARCHAR(40) NOT NULL, -- O TAMANHO SE DEVE AO TAMANHO DO HASH CRIADO PELA CRITOGRAFIA "sha1" DO PHP
	TPUSUARIO         INTEGER     NOT NULL,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

-- TABELA DE CARGOS: DEFINE QUAL TIPO DE USUARIO SE TRATA
CREATE TABLE TIPOUSUARIO (
	CDTPUSU           INTEGER PRIMARY KEY,
	NMTPUSU           VARCHAR(15) NOT NULL,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER,
	CDOPERATUALIZACAO INTEGER
);

-- DEFINE TODOS OS EQUIPAMENTOS QUE PODERÃO SER DISPONIBILIZADOS COMO RECURSOS PARA PROFESSORES E 
-- COORDENADORES. ESTES INCLUEM EQUIPAMENTOS (EX.: COMPUTADORES) OU SALAS (EX.: LABORATÓRIOS)
-- OS CAMPOS DE DSMARCAEQUIP E DSATRIBEQUIP SOMENTE SERAO USADOS PARA EQUIPAMENTOS
-- OS CAMPOS NRPREDIO E NRSALA SERAO USADOS SOMENTE PARA SALAS.
CREATE TABLE RECURSO(
	CDRECURSO         INTEGER     PRIMARY KEY,
	DSRECURSO         VARCHAR(30),
	TPRECURSO         INTEGER     NOT NULL, -- IDENTIFICA O EQUIPAMENTO COMO UM EQUIPAMENTO OU SALA. ESTA IDENTIFICAÇÃO SERÁ FEITA ATRAVÉS DOS INDICES 1 E 2, RESPECTIVAMENTE
	DSMARCAREC        VARCHAR(15),          
	DSATRIBREC        VARCHAR(300),
	NRSALA            INTEGER,
	NRPREDIO          INTEGER,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

CREATE TABLE RESERVA(
	CDRESERVA         INTEGER     PRIMARY KEY,
	CDUSUARIO         INTEGER     NOT NULL,
	DSOCORRENCIA      VARCHAR(1000),
	STATUS            INTEGER 	  NOT NULL, -- CAMPO DE IDENTIFICACAO DO ESTADO ATUAL DA RESERVA: AUXILIA O CONTROLE DO SETOR DA INFRA, A PARTIR DO FATO DE QUE ESTE CAMPO INFORMARÁ SE A RESERVA ESTÁ PENDENTE, JA FOI ATENDIDA, JA FOI CONCLUIDA OU FOI CANCELADA
	NRPREDIOUSO       INTEGER, -- CODIGO DO PREDIO ONDE OS EQUIPAMENTOS DEVERÃO SER DISPONIBILIZADOS.
	NRSALAUSO         INTEGER, -- CODIGO DA SALA ONDE OS EQUIPAMENTOS DEVERÃO SER DISPONIBILIZADOS.
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

-- TABELA DE ITENS DA RESERVA: ASSOCIA TODOS OS ITENS RESERVADOS POR UM PROFESSOR À SUA RESERVA.
CREATE TABLE ITEMRESERVA (
	CDITEMRESERVA     INTEGER PRIMARY KEY,
	CDRESERVA         INTEGER,
	CDRECURSO         INTEGER,
	DTINICIORES		  DATE        NOT NULL, -- DATA DO INICIO DO PERIODO QUE O ITEM ESTARA EMPRESTADO.
	DTPREVDEV         DATE        NOT NULL, -- DATA PREVISTA DE DEVOLUÇÃO DO EQUIPAMENTO AO SETOR DE INFRA.
	HORARIORESER      DATE,                 -- ESTE CAMPO SOMENTE SERA UTIL PARA RESERVAS QUE DUREM SOMENTE O PERIODO DE UMA AULA
	DTDEVOLUCAO       DATE,                 -- DATA REAL DE DEVOLUÇÃO DO EQUIPAMENTO
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

CREATE TABLE DISCIPLINA (
	CDDISCIPLINA      INTEGER PRIMARY KEY,
	NMDISCIPLINA      VARCHAR(40) NOT NULL,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

CREATE TABLE TURMA (
	CDTURMA           INTEGER     PRIMARY KEY,
	NMTURMA           VARCHAR(15) NOT NULL,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

-- TABELA DE HORARIOS: REPRESENTA TODOS OS HORARIOS DISPONIBILIZADOS PELA INSTITUIÇÃO PARA AULAS. 
CREATE TABLE HORARIO (
	CDHORARIO INTEGER PRIMARY KEY,
	DIASEMANA CHAR(3), -- ESTE CAMPO ACEITARÁ SOMENTE OS VALORES 'SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM'
	HORAINICIO DATE,
	HORAFIM    DATE,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL
);

-- DEFINE A GRADE DE HORARIOS DAS TURMAS, ASSOCIANDO DETERMINADA TURMA A UM HORARIO, PROFESSOR E DISCIPLINA
CREATE TABLE HORARIOTURMA (
	CDTURMA           INTEGER,
	CDDISCIPLINA      INTEGER,
	CDPROFESSOR       INTEGER,
	CDHORARIO         INTEGER,
	DTINCLUSAO        DATE        NOT NULL,
	DTATUALIZACAO     DATE        NOT NULL,
	CDOPERINCLUSAO    INTEGER     NOT NULL,
	CDOPERATUALIZACAO INTEGER     NOT NULL,
  CONSTRAINTS PK_HORARIOTURMA PRIMARY KEY(CDTURMA, CDDISCIPLINA, CDPROFESSOR, CDHORARIO)
);

-- CRIAÇÃO DAS RESTRIÇÕES DE INTEGRIDADE
----------------------------------------
--------------- USUARIO ----------------
----------------------------------------
ALTER TABLE USUARIO ADD CONSTRAINT FK_USU_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USU_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USU_TPUSUARIO FOREIGN KEY (TPUSUARIO) REFERENCES TIPOUSUARIO(CDTPUSU);

----------------------------------------
--------------- TIPOUSUARIO ------------
----------------------------------------
ALTER TABLE TIPOUSUARIO ADD CONSTRAINT FK_TPUSU_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE TIPOUSUARIO ADD CONSTRAINT FK_TPUSU_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);

----------------------------------------
--------------- RECURSO ----------------
----------------------------------------
ALTER TABLE RECURSO ADD CONSTRAINT FK_REQ_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE RECURSO ADD CONSTRAINT FK_REQ_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
-- 1.: TIPO DE RECURSO = 'EQUIPAMENTOS EM GERAL'
-- 2.: TIPO DE RECURSO = 'SALA'
ALTER TABLE RECURSO ADD CONSTRAINT CK_REQ_TPREC CHECK (TPRECURSO IN (1, 2));

----------------------------------------
--------------- RESERVA ----------------
----------------------------------------
ALTER TABLE RESERVA ADD CONSTRAINT FK_RES_USUARIO FOREIGN KEY (CDUSUARIO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RES_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RES_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
-- 1.: PENDENTE : A RESERVA FOI CONFIRMADA, PORÉM, O RESPONSÁVEL AINDA NÃO TEVE ACESSO AOS EQUIPAMENTOS.
-- 2.: ANTENDIDO: A RESERVA JÁ FOI FEITA E O EQUIPAMENTO DISPONIBILIZADO PARA O RESPONSÁVEL.
-- 3.: CONCLUIDO: OS ITENS RESERVADOS JÁ FORAM ENTREGUES AO SETOR DE INFRA-ESTRUTURA
-- 4.: CANCELADO: A RESERVA FOI CANCELADA POR UMA DAS DUAS PARTES.
ALTER TABLE RESERVA ADD CONSTRAINT CK_RES_STATUS CHECK(STATUS IN(1, 2, 3, 4));

----------------------------------------
--------------- ITEMRESERVA ------------
----------------------------------------
ALTER TABLE ITEMRESERVA ADD CONSTRAINT FK_ITMRESE_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE ITEMRESERVA ADD CONSTRAINT FK_ITMRESE_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE ITEMRESERVA ADD CONSTRAINT FK_ITMRESE_RESERVA FOREIGN KEY (CDRESERVA) REFERENCES RESERVA(CDRESERVA);
ALTER TABLE ITEMRESERVA ADD CONSTRAINT FK_ITMRESE_RECURSO FOREIGN KEY (CDRECURSO) REFERENCES RECURSO(CDRECURSO);
ALTER TABLE ITEMRESERVA ADD CONSTRAINT CK_DATA_EMP CHECK(DTINICIORES < DTPREVDEV);

----------------------------------------
--------------- DISCIPLINA -------------
----------------------------------------
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DIS_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DIS_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);

----------------------------------------
--------------- TURMA ------------------
----------------------------------------
ALTER TABLE TURMA ADD CONSTRAINT FK_TUR_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE TURMA ADD CONSTRAINT FK_TUR_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);

----------------------------------------
--------------- HORARIO -----------------
----------------------------------------
ALTER TABLE HORARIO ADD CONSTRAINT FK_HOR_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE HORARIO ADD CONSTRAINT FK_HOR_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
-- GARANTE QUE A HORA DE INICIO SEJA ANTES QUE A HORA DE FIM
ALTER TABLE HORARIO ADD CONSTRAINT CK_HOR_HORAAULA CHECK(HORAINICIO < HORAFIM);
ALTER TABLE HORARIO ADD CONSTRAINT CK_HOR_DIAAULA CHECK(DIASEMANA IN('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM'));

----------------------------------------
--------------- HORARIOTURMA -----------
----------------------------------------
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_CDOPERINCL FOREIGN KEY (CDOPERINCLUSAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_CDOPERATU FOREIGN KEY (CDOPERATUALIZACAO) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_TURMA FOREIGN KEY (CDTURMA) REFERENCES TURMA(CDTURMA);
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_DISC FOREIGN KEY (CDDISCIPLINA) REFERENCES DISCIPLINA(CDDISCIPLINA);
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_PROF FOREIGN KEY (CDPROFESSOR) REFERENCES USUARIO(CDUSUARIO);
ALTER TABLE HORARIOTURMA ADD CONSTRAINT FK_HORATURMA_HORA FOREIGN KEY (CDHORARIO) REFERENCES HORARIO(CDHORARIO);


-- INSERINDO DADOS INCICIAIS DO SISTEMA
INSERT INTO TIPOUSUARIO(CDTPUSU, NMTPUSU, DTINCLUSAO, DTATUALIZACAO) VALUES (1, 'INFRA', SYSDATE, SYSDATE);
INSERT INTO TIPOUSUARIO(CDTPUSU, NMTPUSU, DTINCLUSAO, DTATUALIZACAO) VALUES (2, 'PROFESSOR', SYSDATE, SYSDATE);
INSERT INTO TIPOUSUARIO(CDTPUSU, NMTPUSU, DTINCLUSAO, DTATUALIZACAO) VALUES (3, 'COORDENADOR', SYSDATE, SYSDATE);
COMMIT;

INSERT INTO USUARIO(CDUSUARIO, NMUSUARIO, SENHA, TPUSUARIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, 'admin_infra', '356a192b7913b04c54574d18c28d46e6395428ab', 1, SYSDATE, SYSDATE, 1, 1);
INSERT INTO USUARIO(CDUSUARIO, NMUSUARIO, SENHA, TPUSUARIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (2, 'professor_teste', '356a192b7913b04c54574d18c28d46e6395428ab', 1, SYSDATE, SYSDATE, 1, 1);
INSERT INTO USUARIO(CDUSUARIO, NMUSUARIO, SENHA, TPUSUARIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (3, 'coordenador_teste', '356a192b7913b04c54574d18c28d46e6395428ab', 1, SYSDATE, SYSDATE, 1, 1);
COMMIT;

INSERT INTO RECURSO(CDRECURSO, DSRECURSO, TPRECURSO, DSMARCAREC, DSATRIBREC, NRSALA, NRPREDIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, 'PROJETOR', 1, 'DELL', 'resolução 1280x800, conector RJ e capacidade de gerenciamento de rede, luminosidade de 3500 lumens', null, null, SYSDATE, SYSDATE, 1, 1);
INSERT INTO RECURSO(CDRECURSO, DSRECURSO, TPRECURSO, DSMARCAREC, DSATRIBREC, NRSALA, NRPREDIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (2, 'LABORATORIO DE INFORMÁTICA 1', 2, NULL, NULL, 308, 2, SYSDATE, SYSDATE, 1, 1);
COMMIT;

INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, 'SEG', TO_DATE('01/01/2001 07:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (2, 'SEG', TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (3, 'SEG', TO_DATE('01/01/2001 08:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (4, 'SEG', TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (5, 'SEG', TO_DATE('01/01/2001 10:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (6, 'SEG', TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (7, 'SEG', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (8, 'SEG', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (9, 'SEG', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (10, 'SEG', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (11, 'SEG', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (12, 'SEG', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (13, 'SEG', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (14, 'SEG', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (15, 'SEG', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (16, 'SEG', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (17, 'TER', TO_DATE('01/01/2001 07:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (18, 'TER', TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (19, 'TER', TO_DATE('01/01/2001 08:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (20, 'TER', TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (21, 'TER', TO_DATE('01/01/2001 10:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (22, 'TER', TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (23, 'TER', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (24, 'TER', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (25, 'TER', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (26, 'TER', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (27, 'TER', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (28, 'TER', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (29, 'TER', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (30, 'TER', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (31, 'TER', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (32, 'TER', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (33, 'QUA', TO_DATE('01/01/2001 07:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (34, 'QUA', TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (35, 'QUA', TO_DATE('01/01/2001 08:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (36, 'QUA', TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (37, 'QUA', TO_DATE('01/01/2001 10:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (38, 'QUA', TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (39, 'QUA', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (40, 'QUA', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (41, 'QUA', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (42, 'QUA', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (43, 'QUA', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (44, 'QUA', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (45, 'QUA', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (46, 'QUA', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (47, 'QUA', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (48, 'QUA', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (49, 'QUI', TO_DATE('01/01/2001 07:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (50, 'QUI', TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (51, 'QUI', TO_DATE('01/01/2001 08:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (52, 'QUI', TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (53, 'QUI', TO_DATE('01/01/2001 10:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (54, 'QUI', TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (55, 'QUI', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (56, 'QUI', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (57, 'QUI', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (58, 'QUI', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (59, 'QUI', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (60, 'QUI', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (61, 'QUI', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (62, 'QUI', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (63, 'QUI', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (64, 'QUI', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (65, 'SEX', TO_DATE('01/01/2001 07:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (66, 'SEX', TO_DATE('01/01/2001 07:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (67, 'SEX', TO_DATE('01/01/2001 08:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (68, 'SEX', TO_DATE('01/01/2001 09:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (69, 'SEX', TO_DATE('01/01/2001 10:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (70, 'SEX', TO_DATE('01/01/2001 11:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (71, 'SEX', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (72, 'SEX', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (73, 'SEX', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (74, 'SEX', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (75, 'SEX', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (76, 'SEX', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (77, 'SEX', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (78, 'SEX', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (79, 'SEX', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (80, 'SEX', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (81, 'SAB', TO_DATE('01/01/2001 07:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 08:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (82, 'SAB', TO_DATE('01/01/2001 08:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 09:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (83, 'SAB', TO_DATE('01/01/2001 09:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 10:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (84, 'SAB', TO_DATE('01/01/2001 10:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 11:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (85, 'SAB', TO_DATE('01/01/2001 11:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 12:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (86, 'SAB', TO_DATE('01/01/2001 12:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 13:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (87, 'SAB', TO_DATE('01/01/2001 13:30', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (88, 'SAB', TO_DATE('01/01/2001 14:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 15:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (89, 'SAB', TO_DATE('01/01/2001 15:20', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (90, 'SAB', TO_DATE('01/01/2001 16:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 17:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (91, 'SAB', TO_DATE('01/01/2001 17:10', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (92, 'SAB', TO_DATE('01/01/2001 18:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 18:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (93, 'SAB', TO_DATE('01/01/2001 19:00', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (94, 'SAB', TO_DATE('01/01/2001 19:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 20:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (95, 'SAB', TO_DATE('01/01/2001 20:50', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
INSERT INTO HORARIO(CDHORARIO, DIASEMANA, HORAINICIO, HORAFIM, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (96, 'SAB', TO_DATE('01/01/2001 21:40', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2001 22:30', 'DD/MM/YYYY HH24:MI'), SYSDATE, SYSDATE, 1, 1);
COMMIT;

INSERT INTO DISCIPLINA(CDDISCIPLINA, NMDISCIPLINA, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, 'ALGORITMOS E TÉCNICAS DE PROGRAMAÇÃO', SYSDATE, SYSDATE, 1, 1);
INSERT INTO DISCIPLINA(CDDISCIPLINA, NMDISCIPLINA, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (2, 'PROJETO DE SISTEMAS DE INFORMAÇÃO', SYSDATE, SYSDATE, 1, 1);
COMMIT;

INSERT INTO TURMA(CDTURMA, NMTURMA, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, '01/2010', SYSDATE, SYSDATE, 1, 1);
COMMIT;

INSERT INTO HORARIOTURMA(CDTURMA, CDDISCIPLINA, CDPROFESSOR, CDHORARIO, DTINCLUSAO, DTATUALIZACAO, CDOPERINCLUSAO, CDOPERATUALIZACAO) VALUES (1, 1, 2, 1, SYSDATE, SYSDATE, 1, 1);
COMMIT;